### PR TITLE
chore (package.json): allow react15 beside 0.14

### PR DESCRIPTION
**Pull request by ruffle1986**
React sticky box is very useful for us and we'd really like to use it in the future, but we need React 15 support if you don't mind.

Great job, sir! :)

### CODE REVIEW

**Comment by ruffle1986** [comment]
Yes, it does a great job for us. Thanks. Um, when would you like to publish the new version on npm? :)

**Comment by oroce** [comment]
@danielberndt yes we've been using your for couple of months already. We chose this over any other ones because of two reasons:
* react-sticky-box tries to locate the closest scrollable parent rather than just using body as a scrollable view
* it's high performant, it's way faster than the most of the solutions out there

thanks for your great job you've done!

**Comment by danielberndt** [comment]
@ruffle1986 I just released v0.4.9

and thanks for the feedback @oroce :)

I'm using loads of StickyBoxes at my current project (www.codecks.io) so performance is super critical to me. Unfortunately newer versions of chrome added some mechanisms to throttle mousewheel events once the page gets too busy. This leads to fairly unpleasant results. So I guess I have to look even deeper 😳

**Comment by ruffle1986** [comment]
@danielberndt cheers 🍻

**Comment by oroce** [comment]
yeah we've been facing the same issue, os osx the throttling is really annoying. hopefully chrome will support eventually `position: sticky`, and we can have sticky behaviour natively integrated.

**Comment by danielberndt** [comment]
`position: sticky` won't actually solve all the use cases of this component:

I don't know whether you ran across this already, but if you have a <StickyBox> that's higher than the viewport, it's contents will be scrolled as well until the bottom of the StickyBox is visible and only then it'll become sticky. I basically copied the scroll-behaviour of the sidebar in facebook pages like this one: https://www.facebook.com/react

**Comment by danielberndt** [comment]
fyi: I just rewrote basically the whole library to get rid of most of the jank.

There's are some incompatible changes. Feel free take a look at the readme, and let me know if stuff has improved for you, or whether something's broken.

**Comment by oroce** [comment]
@danielberndt sorry for the late reply. Actually I tried it out couple of weeks ago but we failed to move to the new version and not because of `react-sticky-box` rather `react-measure`. I spent couple of hours trying make it detect the right size (basically we were using `width: 100%` inside a `position: relative` element) it wasn't able. So as the next I need to dig deeper in `react-measure` to understand how it calculates the element's width.

I will keep you posted.

**Pull request merged**
